name: Java Build and Deploy Pipeline

on:
  push:
     branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  # 1: Build - tests ##
  build:
   uses: codenest/reusable-java-pipelines/.github/workflows/build-pipeline.yml@main
   secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #3: Deploy to Docker ##
  deploy-docker:
   needs: build
   uses: codenest/reusable-java-pipelines/.github/workflows/docker-deploy.yml@main
   
  
